const { fontFamily } = require("tailwindcss/defaultTheme")

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "washed-green/washed-green-50": "#e9fef8",
        "washed-green/washed-green-100": "#bcfceb",
        "washed-green/washed-green-200": "#9bfae1",
        "washed-green/washed-green-300": "#6ef8d3",
        "washed-green/washed-green-400": "#51f7ca",
        "washed-green/washed-green-500": "#26f5bd",
        "washed-green/washed-green-600": "#23dfac",
        "washed-green/washed-green-700": "#1bae86",
        "washed-green/washed-green-800": "#158768",
        "washed-green/washed-green-900": "#10674f",
        "washed-olive/washed-olive-50": "#eaf4f1",
        "washed-olive/washed-olive-100": "#bddcd3",
        "washed-olive/washed-olive-200": "#9dcbbd",
        "washed-olive/washed-olive-300": "#70b39f",
        "washed-olive/washed-olive-400": "#55a48d",
        "washed-olive/washed-olive-500": "#2a8d70",
        "washed-olive/washed-olive-600": "#268066",
        "washed-olive/washed-olive-700": "#1e6450",
        "washed-olive/washed-olive-800": "#174e3e",
        "washed-olive/washed-olive-900": "#123b2f",
        "primary-green/primary-green-50": "#f2fbf4",
        "primary-green/primary-green-100": "#d7f4de",
        "primary-green/primary-green-200": "#c4eece",
        "primary-green/primary-green-300": "#a9e6b8",
        "primary-green/primary-green-400": "#99e1aa",
        "primary-green/primary-green-500": "#7fda95",
        "primary-green/primary-green-600": "#74c688",
        "primary-green/primary-green-700": "#5a9b6a",
        "primary-green/primary-green-800": "#467852",
        "primary-green/primary-green-900": "#355c3f",
        "brand/brand-washedGreen": "#26f5bd",
        "brand/brand-washedOlive": "#2a8d70",
        "brand/brand-primaryGreen": "#7fda95",
        "brand/brand-dark": "#2d2d2d",
        "Neutrals/neutrals-1": "#ffffff",
        "Neutrals/neutrals-2": "#fdfdfd",
        "Neutrals/neutrals-3": "#f7f7f7",
        "Neutrals/neutrals-4": "#f2f2f2",
        "Neutrals/neutrals-5": "#e0e0e0",
        "Neutrals/neutrals-6": "#cbcbcb",
        "Neutrals/neutrals-7": "#a1a1a1",
        "Neutrals/neutrals-8": "#777777",
        "Neutrals/neutrals-9": "#666666",
        "Neutrals/neutrals-10": "#4d4d4d",
        "Neutrals/neutrals-11": "#464646",
        "Neutrals/neutrals-12": "#3e3e3e",
        "Neutrals/neutrals-13": "#2d2d2d",
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        dm: ["var(--font-dm)", ...fontFamily.serif],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
